version: '3'

networks:
  laravel:

services:
  redis:
    image: redis:latest
    command: redis-server --appendonly yes --replica-read-only no
    volumes:
        - ./data/redis:/data
    ports:
        - "6378:6379"
    networks:
        - laravel
  web:
    image: nginx:stable-alpine
    container_name: nginx_weather_app
    ports:
        - "8080:80"
        - "433:433"
    links:
        - redis
    volumes:
      - .:/var/www/html
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - redis
      - mysql
    networks:
        - laravel

  mysql:
    platform: linux/amd64
    image: mysql:8.0.25
    container_name: mysql_weather_app
    restart: unless-stopped
    ports:
      - "3320:3306"
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: weather_app
      MYSQL_USER: weather_app
      MYSQL_PASSWORD: weather_app
      MYSQL_ROOT_PASSWORD: weather_app
    networks:
      - laravel
  supervisor:
      build:
          context: ./docker/supervisor
          dockerfile: Dockerfile
      container_name: supervisor
      volumes:
          - .:/var/www/html
      networks:
          - laravel
      depends_on:
          - redis
  php:
      build:
          context: ./docker/php
          dockerfile: Dockerfile
      container_name: php_weather_app
      volumes:
          - .:/var/www/html
      ports:
          - "9004:9000"
      depends_on:
          - mysql
          - redis
          - supervisor
      networks:
          - laravel
